### ISSUE TITLE
Built X days ago showing incorrectly

### ISSUE THREAD

**Issue by arowla** [18F/project-monitor#6]
The monitor is showing "built 24 days ago" on OpenFEC, but you can see that his has been built much  more recently than that.

https://travis-ci.org/18F/openFEC/branches

**Comment by monfresh** [comment]
That's because the OpenFEC repo has not added the Travis webhook. Adding a project to Project Monitor requires adding the info to this repo's `projects.json`, as well as adding the notification webhook in the project's own repo, as explained in the [Readme](https://github.com/18F/project-monitor#add-your-project), but I need to update the URL in the Readme.

OpenFEC and Project Monitor are showing up on the site right now because I cheated and simulated a ping from Travis via a `curl` request, but I used an older build in the simulation :)

**Comment by monfresh** [comment]
I just tested this with the latest Project Monitor Travis build (i.e. without cheating), and it works, so I'm closing this. Feel free to reopen if it still doesn't work after you add the webhook to the OpenFEC Travis config, and after you kick off a new Travis build.
